
otp-plugin:
  token: 23f091e8-7800-4275-b3fc-43ddadbe9f4b
  tenant: d41c632c-68d2-457f-b064-c0f479515255
  farsi-reader:
    api-key: TheAPIKey
    api-url: https://api.farsireader.com/ArianaCloudService/ReadTextGET
